version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./html:/usr/share/nginx/html
      - ./css:/usr/share/nginx/html/css
      - ./images:/usr/share/nginx/html/images
      - ./ssl:/etc/nginx/ssl
    restart: unless-stopped
